### ISSUE TITLE
Ensure new EverDrive OS update didn't break anything

### ISSUE THREAD

**Issue by buu342** [buu342/N64-UNFLoader#17]
If it did I will probably cry myself to sleep, no biggie.

**Comment by buu342** [comment]
UNFLoader uploads fine with the 3.0 on the new OS. However, the USB library is broken. Supposedly, a magic value is implemented now, so it's a matter of putting the code in X7 mode if it detects this magic value.

**Comment by buu342** [comment]
Broken on the X7 as well
[WAKE ME UP](https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fl7.alamy.com%2Fzooms%2Fb97675b9a9dd40328247b420c2fc6a7c%2Fman-reading-bible-and-taking-drugs-d0ttnj.jpg&f=1&nofb=1)

**Comment by buu342** [comment]
The samples are out. Time to have some fun:
https://github.com/krikzz/ED64/tree/master/ED64-XIO

**Comment by networkfusion** [comment]
The better resource is in 😁 https://github.com/N64-tools/ED64/ (make sure you keep checking the branches)...

**Comment by buu342** [comment]
Fixed in the most recent commit
https://github.com/buu342/N64-UNFLoader/commit/8c06caa08d0cfe4ff3fe5dc52a3521bffb7a1406
