### ISSUE TITLE
EDX7 + macOS Testing

### ISSUE THREAD

**Issue by danbolt** [buu342/N64-UNFLoader#28]
Did some tests with a more recent version of the library and samples.

I was using
1. EverDrive-64 X7 with OS 3.05
2. macOS Catalina 10.15.7 with the drivers installed as per the guide

ROMs were compiled with N64 SDK Developers Toolkit Version 5.0 (emulated on Windows XP SP3)

### Example 1
```bash
 ~/Projects/N64-UNFLoader/UNFLoader/UNFLoader -r ./unflexa1.n64 -d
```
![Screen Shot 2020-11-26 at 11 18 38 AM](https://user-images.githubusercontent.com/1205433/100386722-14e7a200-2fdb-11eb-8a90-b54ef3215b51.png)

### Example 2
```bash
 ~/Projects/N64-UNFLoader/UNFLoader/UNFLoader -2 ./unflexa4.n64 -d
```
![IMG_0381](https://user-images.githubusercontent.com/1205433/100386754-26c94500-2fdb-11eb-9ddc-e57fc2d01cd6.jpg)
![Screen Shot 2020-11-26 at 11 19 24 AM](https://user-images.githubusercontent.com/1205433/100386758-27fa7200-2fdb-11eb-964a-20ff0da0e505.png)

### Example 3
```bash
 ~/Projects/N64-UNFLoader/UNFLoader/UNFLoader -2 ./unflexa3.n64 -d
```

Had a test file containing:
```
Hello, test
this is a file
```

![Screen Shot 2020-11-26 at 11 22 33 AM](https://user-images.githubusercontent.com/1205433/100386803-49f3f480-2fdb-11eb-90a8-6bb36187d708.png)
![Screen Shot 2020-11-26 at 11 22 50 AM](https://user-images.githubusercontent.com/1205433/100386816-537d5c80-2fdb-11eb-8eae-966dc1ff5f3b.png)

Note I sent a much larger file ([the `spec` file from my 64Brew Jam Submission](https://github.com/danbolt/n64-jam-1/blob/main/spec)) and got the following error:
![Screen Shot 2020-11-26 at 11 21 49 AM](https://user-images.githubusercontent.com/1205433/100386947-a2c38d00-2fdb-11eb-80ec-388d34f22317.png)

Seems like a pretty understandable issue though.

### Example 4
```bash
 ~/Projects/N64-UNFLoader/UNFLoader/UNFLoader -2 ./unflexa4.n64 -d
```

![ex4](https://user-images.githubusercontent.com/1205433/100386986-bd960180-2fdb-11eb-8805-5d632bbcdf32.jpg)

**Comment by buu342** [comment]
Fantastic! Thanks for testing :heart:

**Comment by networkfusion** [comment]
@danbolt It would be great if you can take a look at the new CICD for macOS (https://github.com/buu342/N64-UNFLoader/blob/master/azure-pipelines.yml) and see if you can get it working... It is the only one that doesnt work... so currently commented out.

**Comment by danbolt** [comment]
Sure thing. I might need to check with my employer first if I'm looking
into Azure, so I'll let you know if that's okay.

**Comment by networkfusion** [comment]
@danbolt No need to set up your own... just create a fork and then a PR. any changes you make to the yml will automatically build against this repo. I helped @buu342 get it working 😁

**Comment by networkfusion** [comment]
just as an example... 
![image](https://user-images.githubusercontent.com/11439699/100478352-d76e3c00-30e2-11eb-8403-73db55544af7.png)

**Comment by buu342** [comment]
Reopening to make this issue is easier to find :feelsgood:

**Comment by buu342** [comment]
We can also use this opportunity to flesh out the "How to build UNFLoader on Mac" section.

**Comment by danbolt** [comment]
Hey team, I've set up a potential Azure pipeline here:

https://github.com/buu342/N64-UNFLoader/pull/45

@networkfusion , it seems editing `azure-pipelines.yml` hasn't updated the CI. Perhaps there's something else I need to change on my end?
![Screen Shot 2021-02-13 at 12 45 39 PM](https://user-images.githubusercontent.com/1205433/107861236-61cc5f00-6df9-11eb-9588-653429386987.png)

**Comment by danbolt** [comment]
macOS prevents running unsigned binaries by default. If a user wants to use an unsigned program for the first time, they will need to go to the **Security & Privacy** panel in the System Preferences menu and explicitly allow it to be run.

![IMG_0708](https://user-images.githubusercontent.com/1205433/107863002-b2e25000-6e05-11eb-83ca-81292718c2ce.JPG)

**Comment by buu342** [comment]
Awesome. The Azure builds are setup, and the macOS build instructions are written, so I can go ahead and close this issue. Thanks a lot for the help Daniel :smile:
