### ISSUE TITLE
usb.c freezes the CPU when there is no one listening

### ISSUE THREAD

**Issue by anacierdem** [buu342/N64-UNFLoader#89]
Without the following timeout, the busy function is waiting indefinitely when the serial listener is hung up or not started at all.
```C
static void usb_everdrive_usbbusy() 
{
    u32 timeout = 0;
    u32 val __attribute__((aligned(8)));
    do
    {
        usb_everdrive_readreg(ED_REG_USBCFG, &val);
        if (timeout++ != 8192)
            continue;
        usb_everdrive_writereg(ED_REG_USBCFG, ED_USBMODE_RDNOP);
    } while ((val & ED_USBSTAT_ACT) != 0);
}
```
I am not sure if it is possible to stop listening with the original UNF executable (I presume it is the `-d` flag?) but it should happen if you are logging something say every frame and you terminate the process on computer side. Previously the above fix was removed with #85 as it was causing issues for the original SDK. The fix still exists in [libdragon](https://github.com/DragonMinded/libdragon/blob/39eadbce119ad30182bbd9203db7f491796e7eac/src/usb.c#L1087).

An important difference between the two implementation is that, libdragon does not have threading yet so that might be causing something to break. Maybe having two different implementations for libdragon behind a define guard is an acceptable solution until the root cause is found?

**Comment by buu342** [comment]
Fixed in [b716f17](https://github.com/buu342/N64-UNFLoader/commit/b716f17321222e772579c3ee29cda6f3a2ca962f).
