### ISSUE TITLE
Decouple flashcart communication from UI

### ISSUE THREAD

**Issue by Dragorn421** [buu342/N64-UNFLoader#96]
This issue is about discussing design choices for UNFLoader, or more likely its rewrite

Currently UNFLoader's functions handle both communicating with the flashcarts (such as sending a rom) and the UI (CLI/ncurses)

It would be nice if the two purposes could be split into their own functions, with flashcart comms in their own function without UI handling, and the UI handling functions making use of those comms functions as needed

The purpose would be using the comms functions as an API, for example if I wanted to implement my own UI on top of them, including in other languages such as Python

And also it would probably lead to cleaner code anyway (something like single responsibility principle)

**Comment by buu342** [comment]
Fixed in the rewrite branch. I'll close this issue when it's merged.
